language: objective-c
osx_image: xcode10
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE="WebP.xcworkspace"
    - IOS_FRAMEWORK_SCHEME="WebP iOS"
    - TVOS_FRAMEWORK_SCHEME="WebP tvOS"
    - MACOS_FRAMEWORK_SCHEME="WebP macOS"
    - IOS_SDK=iphonesimulator12.0
    - TVOS_SDK=appletvsimulator12.0
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" POD_LINT="NO"
script:
  - set -o pipefail
  - xcrun simctl list
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild -workspace "$WORKSPACE" -list

  # Build and test Framework in Debug
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty

  # Build Framework in ReleaseTest
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO build | xcpretty

  # Build Example in Debug if specified
  - if [ "$SCHEME" == "$IOS_FRAMEWORK_SCHEME" ]; then
    - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty
  fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
    pod lib lint;
  fi
  # - CheckCocoaPodsQualityIndexes.rb __PROJECT_NAME__
notifications:
  email: false
